<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="APc" name="co.icesi.edu.Integration.JuegosTest" tests="5" failures="0" timestamp="2020-05-12T17:40:58 COT" time="0.000" errors="1">
  <testcase name="testSaveGame2TopicExist" time="0.000" classname="co.icesi.edu.Integration.JuegosTest">
    <skipped/>
  </testcase> <!-- testSaveGame2TopicExist -->
  <testcase name="testSaveGame2SameTimeControl" time="0.000" classname="co.icesi.edu.Integration.JuegosTest">
    <skipped/>
  </testcase> <!-- testSaveGame2SameTimeControl -->
  <testcase name="testSaveGameTemaNotNull" time="0.000" classname="co.icesi.edu.Integration.JuegosTest">
    <skipped/>
  </testcase> <!-- testSaveGameTemaNotNull -->
  <testcase name="setUpGame2" time="0.000" classname="co.icesi.edu.Integration.JuegosTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at co.icesi.edu.Integration.JuegosTest.setUpGame2(JuegosTest.java:78)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:623)
at org.testng.TestRunner.beforeRun(TestRunner.java:613)
at org.testng.TestRunner.run(TestRunner.java:584)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setUpGame2 -->
  <testcase name="testSaveGame2SameStories" time="0.000" classname="co.icesi.edu.Integration.JuegosTest">
    <skipped/>
  </testcase> <!-- testSaveGame2SameStories -->
</testsuite> <!-- co.icesi.edu.Integration.JuegosTest -->
